#!/usr/bin/env php
<?php

use App\Commands;

class __command__Command extends Command
{
    public static array $command = [
      [
        "cmd"       => "__command__",
        "mode"      => "full",
        "class"     => __command__Command::class,
        "fn"        => "main",
      ],
    ];

    public function printHelp()
      {
          return [
            'commands' => [],
            'options'   => [],
            'relation'  => [],
          ];
      }

    public function main()
    {
      echo $this->textGreen("__command__");
    }
}
