#!/usr/bin/env php
<?php

use Apps\Controller;

class __controller__Controller extends Controller
{
  public function index()
  {
    $error =[];

    return $this->view('__controller__', [
      "title"         => "Documnet Title",
      "discription"   => "",
      "keywords"      => "",
      'error'         => $error,
      "message"       => []
    ]);
  }
}
