#!/usr/bin/env php
<?php

use System\Apps\Service;

class __service__Service extends Service
{
    public function Test(array $request): array
    {
        return [
          'status'  => 'ok',
          'data'    => null,
          'error'   => false,
          'headers' => ['HTTP/1.1 200 Oke']
        ];
    }

  public function Test_404(array $request): array
  {
    return $this->error(404);
  }
}

