#!/usr/bin/env php
<?php

use System\Apps\Controller;

class __controller__Controller extends Controller
{
  public function index()
  {
    $error = array();

    return $this->view('__controller__', array (
      "meta"          => array (
        "title"         => "Documnet Title",
        "discription"   => "",
        "keywords"      => ""
      ),
      "contents" => array (
  
      ),
      'error' => $error,
      "message" => array()
    ));
  }
}
